# Generated by Django 3.0.5 on 2020-04-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='observations',
        ),
    ]
