# Generated by Django 3.0.5 on 2020-04-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_participation_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
